version: "3"

services:
  webapp:
    build:
        context: .
        dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py test"
    image: raverat/django-docker:1.0
    depends_on:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: django
      MYSQL_PASSWORD: password